### ISSUE TITLE
"Post-processing 'rest_framework/css/bootstrap.min.css' failed!" on static collection

### ISSUE THREAD

**Issue by gsousa92** [CiviWiki/OpenCiviWiki#1302]
### Description

Hi!

When running `docker-compose exec web python project/manage.py collectstatic` I get the the following output:

```python
Post-processing 'rest_framework/css/bootstrap.min.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'rest_framework/css/bootstrap.min.css.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ff0aaff6880>.

The CSS file 'rest_framework/css/bootstrap.min.css' references a file which could not be found:
  rest_framework/css/bootstrap.min.css.map

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.

```
After searching a bit, found the following [issue](https://github.com/encode/django-rest-framework/issues/4950) on djangorestframework repo, and after downgrading django 4.1.0 to 4.0.7, this issue disappeared, so there's a high chance it's some package mismatch. Should django be downgraded manually as a quick fix for this?

### What should have happened?

`docker-compose exec web python project/manage.py collectstatic` should run properly

### What browser(s) are you seeing the problem on?

Not applicable

**Comment by brylie** [comment]
Try again with the latest `develop` branch.

Also, please use Poetry for project development, as we are temporarily removing Docker support from our developer docs #1307
