### ISSUE TITLE
Fix `notifications` deprecation errors

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1426]
### Description

When running management commands, I see the following deprecation warnings.

```sh
/OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/base/models.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.8.0'):
/OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/views.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/urls.py:9: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

### What should have happened?

There should be no deprecation errors when running management commands.

**Upstream issue**: https://github.com/django-notifications/django-notifications/issues/344

**Comment by DamyanBG** [comment]
Hello, I want to contirbute.

**Comment by brylie** [comment]
Thanks, @DamyanBG! I'll assign you to the issue.

**Comment by DamyanBG** [comment]
@brylie I can't see deprecation warnings when I am executing management commands.

**Comment by DamyanBG** [comment]
I made a PR.

**Comment by DamyanBG** [comment]
Usually I found better solution - I installed packaging and changed distlib with packaging in the files in lib\site-packages\notifications\base\ which have this warning message, but I do not have experience with poetry and I am not able to save the changes.

**Comment by DamyanBG** [comment]
I found that my solution is wrong. I closed my PR. I will restart my work.

**Comment by brylie** [comment]
When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Comment by DamyanBG** [comment]
I opened pull request.

**Comment by wrightdj99** [comment]
Is this issue still needing work? If so, I could try and help.

**Comment by AryanGupta0007** [comment]
Hi i have been trying to solve this issue and set up the project locally while setting up i have a problem as when running poetry install in the root directory i would get this error . pLease Help and please tell if there is any group or channel where i can ask my doubts.  . I would get this error in Powershell :
Poetry could not find a pyproject.toml file in C:\Users\panka\Desktop\KIDS\Aryan\Open Source\open Civi Wiki or its parents

**Comment by brylie** [comment]
What do you see when listing the contents of the directory from where you run the poetry command?

**Comment by AryanGupta0007** [comment]
From your message i understand that what files do i see in the directory i am running this install command . The files i see in the directory are :
CODE_OF_CONDUCT.md  CONTRIBUTING.md  docs/  License.md  poetry.lock  Procfile  project  pytest.ini  README.md  setup.cfg

**Comment by AryanGupta0007** [comment]
i may have misinterpreted your msg if so please correct me . I am just a beginner to open source trying to make my first contribution

**Comment by AryanGupta0007** [comment]
ok i figured it i wasn't in the root directory on the shell . Thanks for the help

**Comment by brylie** [comment]
Yes, it appears there is a `pyproject.toml` in the directory, correct? Can you record a video of your terminal session where you are running those commands? Here is one tool that you can use to record an animated GIF of your PowerShell window: https://gifcap.dev/

**Comment by AryanGupta0007** [comment]
does poetry work on git bash?
it always say poetry not found i have added it to path

**Comment by AryanGupta0007** [comment]
it always say poetry not found i have added it to path

**Comment by AryanGupta0007** [comment]
![Recording 2023-07-01 at 17 32 50](https://github.com/CiviWiki/OpenCiviWiki/assets/111166297/1aebbf03-70be-4f85-a912-83c2157d0512)
see now there is a issue in install pre commit

**Comment by AryanGupta0007** [comment]
I think the virtual env is activating as i tried to run the python manage.py migrate command it says django_extensions not installed

**Comment by brylie** [comment]
Try running `poetry shell` to activate the virtual environment. Refer to the Poetry documentation for adding `poetry` to your operating system path:

```sh
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
```

https://python-poetry.org/docs/#installing-with-the-official-installer

**Comment by AryanGupta0007** [comment]
I had already added Poetry to path before posting the comment here. So the issue still persists

**Comment by brylie** [comment]
Try:

1. `poetry shell`
2. `poetry install`
3. `pre-commit install`

**Comment by AryanGupta0007** [comment]
Ya i did the same : still the issue persists
![2](https://github.com/CiviWiki/OpenCiviWiki/assets/111166297/edab243f-282d-4b56-ad2a-512483b8ea6b)

**Comment by brylie** [comment]
Did you try running `poetry lock --no-update` as the error suggested?

**Comment by AryanGupta0007** [comment]
ya i tried it not working still . Sorry for disturbing you again and again . Thank you for the help

**Comment by brylie** [comment]
Hm, it's genuinely a difficult issue, and I can't help reproduce it since I'm not using PowerShell. It might be good to seek help from the Poetry GitHub issues or StackOverflow, as it seems likely that someone will have encountered a similar issue.

**Comment by AryanGupta0007** [comment]
ok thanks!

**Comment by KanishkaHalder1771** [comment]
Hi, is this issue still open, I would like to contribute then. Thanks

**Comment by KanishkaHalder1771** [comment]
Hi, I am getting a test failure, can someone help on this
```
Found 36 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..........................F..Not Found: /thread/12345/
.......
======================================================================
FAIL: test_anonymous_users_are_redirected_to_landing_page (threads.tests.test_views.BaseViewTests.test_anonymous_users_are_redirected_to_landing_page)
Whether unauthenticated users are redirected to the landing page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Work\OpenSource\OpenCiviWiki\project\threads\tests\test_views.py", line 125, in test_anonymous_users_are_redirected_to_landing_page
    self.assertTemplateUsed(self.response, "base.html")
  File "C:\Users\Kanishka\AppData\Local\pypoetry\Cache\virtualenvs\openciviwiki-IXDF-VAf-py3.11\Lib\site-packages\django\test\testcases.py", line 849, in assertTemplateUsed
    self._assert_template_used(template_name, template_names, msg_prefix, count)
  File "C:\Users\Kanishka\AppData\Local\pypoetry\Cache\virtualenvs\openciviwiki-IXDF-VAf-py3.11\Lib\site-packages\django\test\testcases.py", line 814, in _assert_template_used
    self.assertTrue(
AssertionError: False is not true : Template 'base.html' was not a template used to render the response. Actual template(s) used: landing.html

----------------------------------------------------------------------
Ran 36 tests in 206.326s
```
I ran the debugger on the test, it seems like in `_assert_template_used` method these lines:
```
self.assertTrue(
            template_name in template_names,
            msg_prefix + "Template '%s' was not a template used to render"
            " the response. Actual template(s) used: %s"
            % (template_name, ", ".join(template_names)),
        )
```
`template_name` is "base.html" and `template_names` = ["landing.html"]

**Comment by yawningwinner** [comment]
is this issue still open?
